import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { approvalSchema, artifactContentSchema, downloadArtifact, getJson, postJson, approvalsSchema, promotionPreviewSchema, promotionResultSchema, type Approval, type PromotionPreview } from "./api";

function ApprovalCard({ runId, approval, refresh }: { runId: string; approval: Approval; refresh: () => Promise<unknown> }) {
  const [comment, setComment] = useState(""); const [error, setError] = useState<string>();
  const expired = approval.expires_at !== null && Date.parse(approval.expires_at) <= Date.now();
  async function decide(decision: "approved" | "rejected") { setError(undefined); try { await postJson("/runs/" + runId + "/approvals/" + approval.approval_id + "/decisions", { decision, comment }, approvalSchema); await refresh(); } catch { setError("This decision was not recorded; it may be stale, expired, or unauthorized."); } }
  return <li><h3>{approval.authority}</h3><p>Affects {approval.affected_versions.join(", ")}. {expired ? "This authority request has expired." : approval.expires_at ? "Expires " + approval.expires_at : "No expiry supplied."}</p><label>Comment<textarea value={comment} onChange={(event) => setComment(event.target.value)} /></label><button type="button" disabled={expired} onClick={() => void decide("approved")}>Approve</button><button type="button" disabled={expired} onClick={() => void decide("rejected")}>Reject</button>{error ? <p role="alert">{error}</p> : null}</li>;
}
function Preview({ runId, preview, refresh }: { runId: string; preview: PromotionPreview; refresh: () => Promise<unknown> }) {
  const [version, setVersion] = useState(preview.proposed_version); const [message, setMessage] = useState(""); const [tag, setTag] = useState(true); const [result, setResult] = useState<string>();
  const patch = useQuery({ queryKey: ["promotion-patch", preview.artifact_id, preview.artifact_version], queryFn: () => getJson("/artifacts/" + preview.artifact_id, artifactContentSchema) });
  const eligible = preview.direct_eligible && !preview.conflict_reason && preview.checks.every((check) => check.status === "passed");
  async function confirm() { try { const outcome = await postJson("/runs/" + runId + "/promotions", { preview_hash: preview.preview_hash, version, message, tag, confirm_preview_hash: preview.preview_hash, confirmation_nonce: preview.confirmation_nonce }, promotionResultSchema); setResult(outcome.status === "committed" ? "Created " + outcome.branch + " at " + outcome.commit_hash : "Direct promotion was not applied. Preserved " + (outcome.review_repository_id ?? "a review result") + " at " + (outcome.review_commit ?? "an immutable artifact") + ". " + (outcome.reason ?? outcome.status)); await refresh(); } catch { setResult("Promotion was refused; refresh the immutable preview before trying again."); } }
  return <section aria-label="Promotion preview"><h2>Promotion preview</h2><p>Immutable preview <code>{preview.preview_hash}</code>; confirmation expires {preview.confirmation_expires_at}</p><dl><div><dt>Recorded source baseline</dt><dd><code>{preview.recorded_baseline}</code></dd></div><div><dt>Current source baseline</dt><dd><code>{preview.current_baseline}</code>{preview.current_source_dirty ? " (dirty)" : " (clean)"}</dd></div><div><dt>Proposed target branch</dt><dd><code>{preview.target_branch}</code></dd></div><div><dt>Protected/excluded paths</dt><dd>{preview.protected_paths.join(", ") || "None"}</dd></div></dl><p>{preview.conflict_reason ?? (eligible ? "Eligible for direct promotion." : "Required checks are not complete.")}</p><h3>Changed files</h3><ul>{preview.changed_files.map((file) => <li key={file}>{file}</li>)}</ul><h3>Full immutable diff</h3>{patch.isPending ? <p>Loading validated diff…</p> : patch.isError || patch.data.preview === null ? <p role="alert">The validated diff artifact is unavailable.</p> : <><pre className="promotion-diff" tabIndex={0}>{patch.data.preview}</pre>{patch.data.preview_truncated ? <p>The inline diff is truncated; download the complete {patch.data.size_bytes.toLocaleString()} byte patch.</p> : null}<button type="button" onClick={() => void downloadArtifact(preview.artifact_id).catch(() => setResult("The immutable patch download was not authorized."))}>Download complete validated patch</button><p>Patch SHA-256: <code>{preview.patch_sha256}</code></p></>}<h3>Checks and evidence</h3><ul>{preview.checks.map((check) => <li key={check.name}>{check.name}: {check.status}</li>)}</ul><p>Issues: {preview.issues.join(", ") || "None"}</p><label>Exact version<input value={version} onChange={(event) => setVersion(event.target.value)} /></label><p>The final branch will use this exact version and run ID; changing the version is revalidated by the promotion service.</p><label>Commit message<input value={message} onChange={(event) => setMessage(event.target.value)} /></label><label><input type="checkbox" checked={tag} onChange={(event) => setTag(event.target.checked)} />Create matching tag</label><button type="button" disabled={!eligible || !message.trim() || !version.trim()} onClick={() => void confirm()}>Confirm promotion of this preview</button>{result ? <p role="status">{result}</p> : null}</section>;
}
export function PromotionControls({ runId }: { runId: string }) {
  const approvals = useQuery({ queryKey: ["approvals", runId], queryFn: () => getJson("/runs/" + runId + "/approvals", approvalsSchema) });
  const preview = useQuery({ queryKey: ["promotion", runId], queryFn: () => getJson("/runs/" + runId + "/promotions/current", promotionPreviewSchema), retry: false });
  const [previewError, setPreviewError] = useState<string>();
  async function createPreview() { setPreviewError(undefined); try { await postJson("/runs/" + runId + "/promotion-previews", {}, promotionPreviewSchema); await preview.refetch(); } catch { setPreviewError("Preview creation requires a completed run, user-owned guest input, a user-accepted checkpoint, and an unchanged clean source baseline."); } }
  if (approvals.isPending || preview.isPending) return <p>Loading authority and promotion state…</p>;
  return <section><h1>Approvals and promotion</h1>{approvals.isError ? <p role="alert">Approvals are unavailable.</p> : <ul>{approvals.data.approvals.filter((approval) => approval.status === "pending").map((approval) => <ApprovalCard key={approval.approval_id} runId={runId} approval={approval} refresh={approvals.refetch} />)}</ul>}<button type="button" onClick={() => void createPreview()}>Create immutable preview from latest user checkpoint</button>{previewError ? <p role="alert">{previewError}</p> : null}{preview.isError ? <p>No promotion preview is currently available.</p> : <Preview runId={runId} preview={preview.data} refresh={preview.refetch} />}</section>;
}
