import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import RFB from "@novnc/novnc/lib/rfb";
import { getJson, postJson, checkpointsSchema, desktopSchema, desktopStateSchema, previewsSchema, rollbackPreviewSchema, workspaceSchema, type Workspace } from "./api";

function CopyPolicy({ workspace }: { workspace: Workspace }) { return <section aria-label="Copy policy"><h2>Copy policy and guest health</h2><p>Source fingerprint: <code>{workspace.source_fingerprint}</code></p><p>Excluded: {workspace.excluded_paths.join(", ") || "None"}</p><p>Protected: {workspace.protected_paths.join(", ") || "None"}</p><dl><div><dt>VM</dt><dd>{workspace.health.vm}</dd></div><div><dt>SSH</dt><dd>{workspace.health.ssh}</dd></div><div><dt>Browser</dt><dd>{workspace.health.browser}</dd></div><div><dt>Egress</dt><dd>{workspace.health.egress}</dd></div></dl></section>; }
function Checkpoints({ runId }: { runId: string }) {
  const query = useQuery({ queryKey: ["checkpoints", runId], queryFn: () => getJson("/runs/" + runId + "/workspace/checkpoints", checkpointsSchema) }); const [target, setTarget] = useState<string>(); const [error, setError] = useState<string>();
  const preview = useQuery({ queryKey: ["rollback-preview", runId, target], enabled: Boolean(target), queryFn: () => getJson("/runs/" + runId + "/workspace/checkpoints/" + target + "/rollback-preview", rollbackPreviewSchema) });
  async function rollback() { if (!target) return; setError(undefined); try { await postJson("/runs/" + runId + "/workspace/checkpoints/" + target + "/rollback", { confirm: true }, checkpointsSchema); await query.refetch(); setTarget(undefined); } catch { setError("Rollback was not applied. Refresh the checkpoint state before trying again."); } }
  async function createCheckpoint() { setError(undefined); try { await postJson("/runs/" + runId + "/workspace/checkpoints", {}, checkpointsSchema); await query.refetch(); } catch { setError("A user checkpoint requires current guest input ownership and a ready workspace."); } }
  if (query.isPending) return <p>Loading checkpoints…</p>; if (query.isError) return <p role="alert">Checkpoint state is unavailable.</p>;
  const selected = query.data.checkpoints.find((checkpoint) => checkpoint.checkpoint_id === target);
  const current = query.data.checkpoints.find((checkpoint) => checkpoint.checkpoint_id === query.data.current_checkpoint_id);
  return <section aria-label="Checkpoints"><h2>Checkpoints</h2><button type="button" onClick={() => void createCheckpoint()}>Record user-accepted checkpoint</button><ul>{query.data.checkpoints.map((checkpoint) => <li key={checkpoint.checkpoint_id}><label><input type="radio" checked={target === checkpoint.checkpoint_id} onChange={() => setTarget(checkpoint.checkpoint_id)} name="rollback-target" />{checkpoint.kind} — <code>{checkpoint.commit_hash}</code>{checkpoint.checkpoint_id === query.data.current_checkpoint_id ? " (current)" : ""}</label><small>Design v{checkpoint.design_version}{checkpoint.work_node_id ? "; work node " + checkpoint.work_node_id : ""}; tree <code>{checkpoint.tree_hash}</code>; evidence {checkpoint.evidence_ids.join(", ") || "none"}</small></li>)}</ul>{selected ? <><h3>Rollback preview</h3><p role="status">Guest state will move from <code>{current?.commit_hash ?? "current working tree"}</code> to <code>{selected.commit_hash}</code>. Host files and prior authoritative history are unaffected; a new rollback lineage record will be added.</p>{preview.isPending ? <p>Calculating changed files…</p> : preview.isError ? <p role="alert">The rollback file preview is unavailable; confirmation is disabled.</p> : preview.data.changed_paths.length === 0 ? <p>No tracked files differ between these checkpoints.</p> : <ul>{preview.data.changed_paths.map((item) => <li key={item.path}><code>{item.status}</code> {item.path}</li>)}</ul>}<button type="button" disabled={!preview.data || preview.isError} onClick={() => void rollback()}>Confirm rollback to selected checkpoint</button></> : null}{error ? <p role="alert">{error}</p> : null}</section>;
}
function Desktop({ runId }: { runId: string }) {
  const query = useQuery({ queryKey: ["desktop", runId], queryFn: () => postJson("/runs/" + runId + "/workspace/desktop-sessions", {}, desktopSchema) }); const [error, setError] = useState<string>();
  async function changeOwner(owner: "USER" | "AGENT") { setError(undefined); try { const state = await postJson("/runs/" + runId + "/workspace/input-owner", { owner }, desktopStateSchema); if (state.input_owner === "PAUSED") setError("Automation is stopping at its next safe stage boundary. Take control again when the state remains paused."); await query.refetch(); } catch { setError("Input ownership did not change. The displayed state remains authoritative."); } }
  if (query.isPending) return <p>Connecting guest desktop…</p>; if (query.isError) return <section aria-label="Guest desktop"><p role="alert">Desktop is unavailable or its session expired.</p><button type="button" onClick={() => void query.refetch()}>Request a new session</button></section>;
  const desktop = query.data; return <section aria-label="Guest desktop"><h2>Guest desktop</h2><p>Input owner: {desktop.input_owner}; session expires {desktop.expires_at}</p><button type="button" disabled={desktop.input_owner === "USER"} onClick={() => void changeOwner("USER")}>Take control (pause automation)</button><button type="button" disabled={desktop.input_owner === "AGENT"} onClick={() => void changeOwner("AGENT")}>Return to agent</button><button type="button" onClick={() => void query.refetch()}>Reconnect with a new short-lived session</button>{error ? <p role="status">{error}</p> : null}<DesktopDisplay websocketUrl={desktop.websocket_url} viewOnly={desktop.input_owner !== "USER"} /></section>;
}

function ApplicationPreviews({ runId }: { runId: string }) {
  const query = useQuery({ queryKey: ["previews", runId], queryFn: () => getJson("/runs/" + runId + "/workspace/previews", previewsSchema), refetchInterval: 15_000 });
  if (query.isPending) return <p>Discovering allowlisted guest application ports…</p>;
  if (query.isError) return <p role="alert">Application preview status is unavailable.</p>;
  return <section aria-label="Application previews"><h2>Application previews</h2>{query.data.previews.length === 0 ? <p>No allowlisted guest application port is active.</p> : <ul>{query.data.previews.map((preview) => <li key={preview.port}><a href={preview.url} target="_blank" rel="noreferrer">{preview.label}</a> (short-lived)</li>)}</ul>}</section>;
}

function DesktopDisplay({ websocketUrl, viewOnly }: { websocketUrl: string; viewOnly: boolean }) {
  const target = useRef<HTMLDivElement>(null); const [status, setStatus] = useState("Connecting to the disposable guest display…");
  useEffect(() => { if (!target.current) return; const url = new URL(websocketUrl, window.location.href); url.protocol = window.location.protocol === "https:" ? "wss:" : "ws:"; const rfb = new RFB(target.current, url.toString(), { shared: false }); rfb.viewOnly = viewOnly; rfb.scaleViewport = true; rfb.resizeSession = false; rfb.focusOnClick = true; const connected = () => setStatus(viewOnly ? "Guest display connected in view-only mode." : "Guest display connected with user input enabled."); const disconnected = () => setStatus("Guest display disconnected. Request a new short-lived session to reconnect."); rfb.addEventListener("connect", connected); rfb.addEventListener("disconnect", disconnected); return () => { rfb.removeEventListener("connect", connected); rfb.removeEventListener("disconnect", disconnected); rfb.disconnect(); if (target.current) target.current.replaceChildren(); }; }, [viewOnly, websocketUrl]);
  return <div className="desktop-frame"><p className="sr-only" role="status">{status}</p><div ref={target} aria-label="Authenticated guest desktop display" /></div>;
}
export function WorkspaceControls({ runId }: { runId: string }) {
  const workspace = useQuery({ queryKey: ["workspace", runId], queryFn: () => getJson("/runs/" + runId + "/workspace", workspaceSchema) });
  if (workspace.isPending) return <p>Preparing guest workspace…</p>; if (workspace.isError) return <p role="alert">Workspace is not ready yet.</p>;
  return <><CopyPolicy workspace={workspace.data} /><Desktop runId={runId} /><ApplicationPreviews runId={runId} /><Checkpoints runId={runId} /></>;
}
